# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ]; # depend de l'hote
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-1c692c5c-d45f-4249-b3a9-5dd1ba3de619";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-1c692c5c-d45f-4249-b3a9-5dd1ba3de619".device = "/dev/disk/by-uuid/1c692c5c-d45f-4249-b3a9-5dd1ba3de619";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6E5E-32D1";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
